<?php

namespace Database\Seeders;

use App\Models\Medicine;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MedicineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks, truncate, then re-enable
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('medicines')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $medicines = [
            ['nama_obat' => 'ACETYLCYSTEINE 200 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ACIFAR 200 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ACIFAR 400 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ALERZIN 10 mg', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'ALERZIN SYRUP 60 ml', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'ALPHAMOL', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ALSTEIN 200 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'AMBROXOL 30 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'AMOSTERA 500 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'AMPISTERRA 500 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ANACOF 500 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ANASTAN FORTE 500 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ARBUPON 400 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ARMACORT CREAM', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'ARTIMATIC 20 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ASAM FOLAT 1 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ASTHERIN 2.5 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ATMACID SYR', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'ATORVASTATIN 20 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'AXOFEN SUSP 60 ml', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'BENEURON', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'BENOSTAN 500 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'BETAHISTIN 6 mg', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'BETAMIN 100 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'BETAMOL 500 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'BIMACTRIM', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'BIMACTRIM FORTE', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'BIMAFLOX 500 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'BIOLYSIN', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'BIOMOM', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'BIOPRADYN', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'BISOPROLOL FUMARATE 2.5 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'BISOPROLOL FUMARATE 5 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'BROADAMOX 500 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'BROADAPEN 500 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'BROMIFAR PLUS SYR', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'BUFACARYL', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'BUFANTACID', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'BUFANTACID FORTE SUSPENSI 60 ml', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'BUNDAVIN', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'CALCEO', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'CALCI-5', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'CALCIUM LACTATE 500 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'CALFERA', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'CALORTUSIN', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'CANDESARTAN 16 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'CARDIPIN 10 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'CARDIPIN 5 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'CARGESIK 500 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'CARMESON 4 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'CARMESON 8 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'CARSIDA', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'CARSIDA SUSP 60 ml', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'CEFFORD FORTE 250 DS', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'CEFFORD FORTE 500 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'CEFIXIME 200 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'CIPROFLOXACIN 500 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'CLIMDANYCIN 300 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'CLONADERM CREAM 5 GR', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'CLOPIDOGREL 75 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => "COD LIVER OIL 50'S", 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'COLDREXIN SYR 60 ml', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'COLIPRED CREAM 5 GR', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'COPARCETINE', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'COPARCETINE KID COUGH SYR 60 ml', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'COPARCETINE ORANGE 60 ml', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'COPARCETINE 60 ml', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'CORIC 100 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'CORIC 300 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'CORIZINE 10 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'CORTAVAS 10 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'CORTAVAS 20 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'COSTAN FORTE 500 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'COTRIMOXAZOLE', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'DEXTAF', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'DEXTEEM PLUS', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'DEXTRAL SYRUP 60 ml', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'DOMPERIDONE 10 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'DOMPERIDONE MALEATE 10 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'EPERISONE HCL 50 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ERPHAFLAM 50 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ETAFEN 400 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'FENAMIN 500 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'GASELA 150 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'GENTAMICIN SULFATE 0.1% 5 GR CREAM', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'GENTAMICIN SULFATE CREAM', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'GRAFAZOL 500 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'GRAZEO 20 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'HUFADON SUSP 60 ml', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'HUFAMAG PLUS', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'HUFAXOL 30 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'INFATRIM', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'KATERGI 50 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ILPHIL 500 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'LEXACORT 5 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'LEXACROL TABLET', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'LEXAPRAM 10 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'LOPERAMIDE HCL 2 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'MASTATIN 10 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'MASTATIN 20 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'MELOXICAM 15 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'MELOXICAM 7.5 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'METFORMIN 500 mg TAB', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'METFORMIN HCL 850 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'METISOL 4 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'METRONIDAZOLE 500 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'MEXON', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'MIRACLOVEN 50 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'MIRAPECT 30 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'MOLAPECT 30 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'NEURODEX', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'NOVADEX 0.5 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'NOVADEX 0.75 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'NOVAGESIC FORTE TAB', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'NOVAGESIC SYR 60 ml', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'NOVAMAG TAB', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'NOVASTAN 500 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'OXCAM 15 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'PIRACETAM 1200 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'PIRACETAM 800 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'PIROCAM 20 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'PRITACORT', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'PROSIS SUSPENSI 60 ml', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'PROSTIMIX 100 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'PURINIC 100 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'SAMCOXOL 30 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'SAMTACID', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'SELESMOL 500 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'SELESTRIM TAB', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'SELPYRON', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'SEVOS 8 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'STIMUNO FORTE CAPS', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'STIMUNO SYRUP 100 ml', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'VOLTADEX 50 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'VOSEA', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ZENGESIC', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ZENIREX SYR 60 ml', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'ZEPRAZOL 20 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ZORALIN 2% CREAM 10 GR', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'ZORALIN 200 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'SELEBROX 30 mg', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'Mefenamic Acid 500 mg', 'stok' => 20, 'lokasi' => 'A1'],
            ['nama_obat' => 'Divoltar Diclofenac Sodium 50 mg', 'stok' => 20, 'lokasi' => 'A1'],
            ['nama_obat' => 'Ketorolac Trometamol', 'stok' => 20, 'lokasi' => 'A1'],
            ['nama_obat' => 'Prostanac 50', 'stok' => 20, 'lokasi' => 'A1'],
            ['nama_obat' => 'Opistan 500', 'stok' => 20, 'lokasi' => 'A1'],
            ['nama_obat' => 'Renadinac 50', 'stok' => 30, 'lokasi' => 'A1'],
            ['nama_obat' => 'Diclofenac Sodium', 'stok' => 20, 'lokasi' => 'A1'],
            ['nama_obat' => 'Ibuprofen 400', 'stok' => 40, 'lokasi' => 'A1'],
            ['nama_obat' => 'Cataflam', 'stok' => 30, 'lokasi' => 'A1'],
            ['nama_obat' => 'Ponstan Asam Mefenamat', 'stok' => 30, 'lokasi' => 'A1'],
            ['nama_obat' => 'Antalgin', 'stok' => 30, 'lokasi' => 'A1'],
            ['nama_obat' => 'Piroxicam', 'stok' => 20, 'lokasi' => 'A2'],
            ['nama_obat' => 'Faxiden 20', 'stok' => 20, 'lokasi' => 'A2'],
            ['nama_obat' => 'Melogra 15', 'stok' => 20, 'lokasi' => 'A2'],
            ['nama_obat' => 'Meloxicam', 'stok' => 20, 'lokasi' => 'A2'],
            ['nama_obat' => 'Allopurinol 300 mg', 'stok' => 10, 'lokasi' => 'A2'],
            ['nama_obat' => 'Allopurinol 100 mg', 'stok' => 10, 'lokasi' => 'A2'],
            ['nama_obat' => 'Triamcinolone', 'stok' => 20, 'lokasi' => 'A2'],
            ['nama_obat' => 'Methylprednisolone', 'stok' => 20, 'lokasi' => 'A2'],
            ['nama_obat' => 'Voltadex', 'stok' => 20, 'lokasi' => 'A2'],
            ['nama_obat' => 'Lanadexon', 'stok' => 20, 'lokasi' => 'A2'],
            ['nama_obat' => 'Molacort', 'stok' => 20, 'lokasi' => 'A2'],
            ['nama_obat' => 'Carbidu 0,75', 'stok' => 30, 'lokasi' => 'A2'],
            ['nama_obat' => 'Carbidu 0,5', 'stok' => 30, 'lokasi' => 'A2'],
            ['nama_obat' => 'Atorvastatin Calcium Trihydrate', 'stok' => 30, 'lokasi' => 'A3'],
            ['nama_obat' => 'Simvastatin', 'stok' => 40, 'lokasi' => 'A3'],
            ['nama_obat' => 'Metformin HCl', 'stok' => 20, 'lokasi' => 'A3'],
            ['nama_obat' => 'Gludepatic', 'stok' => 20, 'lokasi' => 'A3'],
            ['nama_obat' => 'Acarbose', 'stok' => 20, 'lokasi' => 'A3'],
            ['nama_obat' => 'Renabetic', 'stok' => 20, 'lokasi' => 'A3'],
            ['nama_obat' => 'Glimepiride 3 mg', 'stok' => 20, 'lokasi' => 'A3'],
            ['nama_obat' => 'Glimepiride 2 mg', 'stok' => 20, 'lokasi' => 'A3'],
            ['nama_obat' => 'Salbutamol Sulfate 2 mg', 'stok' => 20, 'lokasi' => 'A3'],
            ['nama_obat' => 'Teosal Salbutamol Sulfate', 'stok' => 20, 'lokasi' => 'A3'],
            ['nama_obat' => 'Salbutamol Sulfate 4 mg', 'stok' => 20, 'lokasi' => 'A3'],
            ['nama_obat' => 'Glucovance', 'stok' => 20, 'lokasi' => 'A3'],
            ['nama_obat' => 'Gemfibrozil', 'stok' => 20, 'lokasi' => 'A2'],
            ['nama_obat' => 'Neuralgin', 'stok' => 30, 'lokasi' => 'A4'],
            ['nama_obat' => 'Pronicy', 'stok' => 20, 'lokasi' => 'A4'],
            ['nama_obat' => 'Propylthiouracil', 'stok' => 20, 'lokasi' => 'A4'],
            ['nama_obat' => 'Novachlor', 'stok' => 20, 'lokasi' => 'A4'],
            ['nama_obat' => 'Eperisone HCl 50 mg', 'stok' => 20, 'lokasi' => 'A4'],
            ['nama_obat' => 'Aciclovir', 'stok' => 20, 'lokasi' => 'A4'],
            ['nama_obat' => 'Andalut', 'stok' => 30, 'lokasi' => 'A4'],
            ['nama_obat' => 'Eperisone HCl 50 mg', 'stok' => 20, 'lokasi' => 'A4'],
            ['nama_obat' => 'Primolut N', 'stok' => 20, 'lokasi' => 'A4'],
            ['nama_obat' => 'Sildenafil Citrate', 'stok' => 20, 'lokasi' => 'A4'],
            ['nama_obat' => 'Catarent', 'stok' => 20, 'lokasi' => 'A4'],
            ['nama_obat' => 'Cendo Xitrol', 'stok' => 20, 'lokasi' => 'A4'],
            ['nama_obat' => 'Cenfresh', 'stok' => 20, 'lokasi' => 'A4'],
            ['nama_obat' => 'Reco Chloramphenicol', 'stok' => 20, 'lokasi' => 'A4'],
            ['nama_obat' => 'Erlamycetin', 'stok' => 20, 'lokasi' => 'A4'],
            ['nama_obat' => 'Krim Pi Kang Shuang', 'stok' => 10, 'lokasi' => 'A4'],
            ['nama_obat' => 'Ciprofloxacin HCl Monohydrate', 'stok' => 20, 'lokasi' => 'B1'],
            ['nama_obat' => 'Clindamycin Hydrochloride', 'stok' => 20, 'lokasi' => 'B1'],
            ['nama_obat' => 'Cefixime Trihydrate 100 mg', 'stok' => 20, 'lokasi' => 'B1'],
            ['nama_obat' => 'Super Tetra', 'stok' => 20, 'lokasi' => 'B1'],
            ['nama_obat' => 'Amoxicillin Trihydrate', 'stok' => 40, 'lokasi' => 'B1'],
            ['nama_obat' => 'Cefixime Trihydrate Syrup', 'stok' => 10, 'lokasi' => 'B1'],
            ['nama_obat' => 'Amoxsan Syrup', 'stok' => 10, 'lokasi' => 'B1'],
            ['nama_obat' => 'Cefadroxil Monohydrate', 'stok' => 20, 'lokasi' => 'B1'],
            ['nama_obat' => 'Azithromycin Dihydrate', 'stok' => 20, 'lokasi' => 'B1'],
            ['nama_obat' => 'Yusimox', 'stok' => 20, 'lokasi' => 'B1'],
            ['nama_obat' => 'Lerzin Cetirizine', 'stok' => 30, 'lokasi' => 'B2'],
            ['nama_obat' => 'Cetirizine Hydrochloride', 'stok' => 30, 'lokasi' => 'B2'],
            ['nama_obat' => 'Dextamine', 'stok' => 30, 'lokasi' => 'B2'],
            ['nama_obat' => 'Mycoral 200 mg', 'stok' => 30, 'lokasi' => 'B2'],
            ['nama_obat' => 'Mexon Sirup', 'stok' => 10, 'lokasi' => 'B2'],
            ['nama_obat' => 'Dexteem Plus', 'stok' => 20, 'lokasi' => 'B2'],
            ['nama_obat' => 'Mexon Tablet', 'stok' => 20, 'lokasi' => 'B2'],
            ['nama_obat' => 'Loratadine', 'stok' => 20, 'lokasi' => 'B2'],
            ['nama_obat' => 'Bufacaryl', 'stok' => 20, 'lokasi' => 'B2'],
            ['nama_obat' => 'Ketoconazole', 'stok' => 30, 'lokasi' => 'B2'],
            ['nama_obat' => 'OGB Dexa Ketoconazole', 'stok' => 30, 'lokasi' => 'B2'],
            ['nama_obat' => 'Zoralin Ketoconazole', 'stok' => 30, 'lokasi' => 'B2'],
            ['nama_obat' => 'Rhinos SR', 'stok' => 20, 'lokasi' => 'B2'],
            ['nama_obat' => 'Otilon', 'stok' => 20, 'lokasi' => 'B2'],
            ['nama_obat' => 'Furosemide', 'stok' => 20, 'lokasi' => 'B3'],
            ['nama_obat' => 'Spironolacton 25', 'stok' => 20, 'lokasi' => 'B3'],
            ['nama_obat' => 'Ventolin Nebules 2.5 mg', 'stok' => 20, 'lokasi' => 'B3'],
            ['nama_obat' => 'Tremenza', 'stok' => 20, 'lokasi' => 'B3'],
            ['nama_obat' => 'Omeprazole', 'stok' => 30, 'lokasi' => 'B3'],
            ['nama_obat' => 'FG Troches Meiji', 'stok' => 20, 'lokasi' => 'B3'],
            ['nama_obat' => 'Lansoprazole', 'stok' => 30, 'lokasi' => 'B3'],
            ['nama_obat' => 'Ranitidine HCl 150 mg', 'stok' => 30, 'lokasi' => 'B3'],
            ['nama_obat' => 'Isprinol Syrup', 'stok' => 10, 'lokasi' => 'B4'],
            ['nama_obat' => 'Mupirocin Calcium Krim', 'stok' => 20, 'lokasi' => 'B4'],
            ['nama_obat' => 'Nebacetin Ointment', 'stok' => 20, 'lokasi' => 'B4'],
            ['nama_obat' => 'Gentamicin Sulfate', 'stok' => 20, 'lokasi' => 'B4'],
            ['nama_obat' => 'Bevalex Krim', 'stok' => 10, 'lokasi' => 'B4'],
            ['nama_obat' => 'Visan Cort Cream', 'stok' => 10, 'lokasi' => 'B4'],
            ['nama_obat' => 'Genoint Gentamicin Sulfate', 'stok' => 20, 'lokasi' => 'B4'],
            ['nama_obat' => 'Benoson', 'stok' => 20, 'lokasi' => 'B4'],
            ['nama_obat' => 'Zensoderm', 'stok' => 20, 'lokasi' => 'B4'],
            ['nama_obat' => 'Cinolon', 'stok' => 20, 'lokasi' => 'B4'],
            ['nama_obat' => 'Betason N', 'stok' => 20, 'lokasi' => 'B4'],
            ['nama_obat' => 'Vaslone', 'stok' => 20, 'lokasi' => 'B4'],
            ['nama_obat' => 'Betamethasone Valerate', 'stok' => 30, 'lokasi' => 'B4'],
            ['nama_obat' => 'Hydrocortisone Acetate', 'stok' => 30, 'lokasi' => 'B4'],
            ['nama_obat' => 'Borraginol N', 'stok' => 20, 'lokasi' => 'B4'],
            ['nama_obat' => 'Scabimite Cream', 'stok' => 10, 'lokasi' => 'B4'],
            ['nama_obat' => 'Medi-Klin', 'stok' => 20, 'lokasi' => 'B4'],
            ['nama_obat' => 'Sagestam', 'stok' => 20, 'lokasi' => 'B4'],
            ['nama_obat' => 'Candistin', 'stok' => 20, 'lokasi' => 'C1'],
            ['nama_obat' => 'Vometa FT', 'stok' => 20, 'lokasi' => 'C1'],
            ['nama_obat' => 'Ondansetron HCl Dihydrate', 'stok' => 20, 'lokasi' => 'C1'],
            ['nama_obat' => 'Domperidone Maleate', 'stok' => 20, 'lokasi' => 'C1'],
            ['nama_obat' => 'Tranexamic Acid', 'stok' => 20, 'lokasi' => 'C1'],
            ['nama_obat' => 'Andalan Laktasi', 'stok' => 10, 'lokasi' => 'C1'],
            ['nama_obat' => 'Andalan Fe', 'stok' => 10, 'lokasi' => 'C1'],
            ['nama_obat' => 'Andalan Pil KB', 'stok' => 10, 'lokasi' => 'C1'],
            ['nama_obat' => 'Microgynon', 'stok' => 20, 'lokasi' => 'C1'],
            ['nama_obat' => 'Amlodipine Besilate 10 mg', 'stok' => 30, 'lokasi' => 'C2'],
            ['nama_obat' => 'Amlodipine Besilate 5 mg', 'stok' => 30, 'lokasi' => 'C2'],
            ['nama_obat' => 'Candesartan Cilexetil', 'stok' => 20, 'lokasi' => 'C2'],
            ['nama_obat' => 'Valsartan', 'stok' => 20, 'lokasi' => 'C2'],
            ['nama_obat' => 'Bisoprolol Fumarate', 'stok' => 20, 'lokasi' => 'C2'],
            ['nama_obat' => 'Ramipril', 'stok' => 20, 'lokasi' => 'C2'],
            ['nama_obat' => 'Isosorbide Dinitrate', 'stok' => 20, 'lokasi' => 'C2'],
            ['nama_obat' => 'Nitrokaf Retard', 'stok' => 20, 'lokasi' => 'C2'],
            ['nama_obat' => 'Propranolol HCl', 'stok' => 20, 'lokasi' => 'C2'],
            ['nama_obat' => 'Captopril', 'stok' => 30, 'lokasi' => 'C2'],
            ['nama_obat' => 'Asplets', 'stok' => 20, 'lokasi' => 'C2'],
            ['nama_obat' => 'Thrombo Asplets', 'stok' => 20, 'lokasi' => 'C2'],
            ['nama_obat' => 'Mucos Ambroxol HCl', 'stok' => 30, 'lokasi' => 'C3'],
            ['nama_obat' => 'Comtusi', 'stok' => 20, 'lokasi' => 'C3'],
            ['nama_obat' => 'Ambroxol HCl', 'stok' => 30, 'lokasi' => 'C3'],
            ['nama_obat' => 'Acetylcysteine', 'stok' => 20, 'lokasi' => 'C3'],
            ['nama_obat' => 'Scopma', 'stok' => 20, 'lokasi' => 'C3'],
            ['nama_obat' => 'Novadium', 'stok' => 20, 'lokasi' => 'C3'],
            ['nama_obat' => 'Imodium HCl', 'stok' => 20, 'lokasi' => 'C3'],
            ['nama_obat' => 'Lodia', 'stok' => 20, 'lokasi' => 'C3'],
            ['nama_obat' => 'Cotrimoxazole', 'stok' => 20, 'lokasi' => 'C3'],
            ['nama_obat' => 'Spasminal', 'stok' => 20, 'lokasi' => 'C3'],
            ['nama_obat' => 'Griseofulvin', 'stok' => 20, 'lokasi' => 'C3'],
            ['nama_obat' => 'Metronidazole', 'stok' => 20, 'lokasi' => 'C3'],
            ['nama_obat' => 'Neurobion', 'stok' => 40, 'lokasi' => 'C4'],
            ['nama_obat' => 'Gabapentin', 'stok' => 20, 'lokasi' => 'C4'],
            ['nama_obat' => 'Mecobalamin', 'stok' => 30, 'lokasi' => 'C4'],
            ['nama_obat' => 'Dramamine', 'stok' => 30, 'lokasi' => 'C4'],
            ['nama_obat' => 'Betahistine Mesilate', 'stok' => 20, 'lokasi' => 'C4'],
            ['nama_obat' => 'Proris Ibuprofen', 'stok' => 40, 'lokasi' => 'C4'],
            ['nama_obat' => 'Bufect Forte Ibuprofen', 'stok' => 40, 'lokasi' => 'C4'],

            // From medicine_data.xlsx
            ['nama_obat' => 'ABDELOX 500 MG', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'ACYCLOVIR 200 MG', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ACYCLOVIR 400 MG', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'AMBROXOL SYRUP', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'AMOXICILLIN 500 MG', 'stok' => 40, 'lokasi' => '-'],
            ['nama_obat' => 'ANTIMO', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ASAM MEFENAMAT 500 MG', 'stok' => 40, 'lokasi' => '-'],
            ['nama_obat' => 'ASTHIN FORCE 6', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'AZITHROMYCIN 500 MG', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'BETAMETHASONE CREAM', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'B-COMPLEX', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'BISOPROLOL 5 MG', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'BRAXIDIN', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'CAPTOPRIL 12.5 MG', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'CAPTOPRIL 25 MG', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'CEFADROXIL 500 MG', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'CHLORPHENIRAMINE (CTM)', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'COTRIMOXAZOLE 480 MG', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'DEXAMETHASONE 0.5 MG', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'DIGOXIN 0.25 MG', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ENALAPRIL 5 MG', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ERYTHROMYCIN 500 MG', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ETORICOXIB 90 MG', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'FLUCONAZOLE 150 MG', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'FUROSEMIDE 40 MG', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'GEMFIBROZIL 300 MG', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'GLIBENCLAMIDE 5 MG', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'GLICLAZIDE 80 MG', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'GUAIFENESIN 100 MG', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'HALOPERIDOL 1.5 MG', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'HYDROCHLOROTHIAZIDE (HCT) 25 MG', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ISOSORBIDE DINITRATE (ISDN) 5 MG', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'ITRACONAZOLE 100 MG', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'KETOCONAZOLE 200 MG', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'KETOCONAZOLE CREAM', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'LANSOPRAZOLE 30 MG', 'stok' => 40, 'lokasi' => '-'],
            ['nama_obat' => 'LORATADINE 10 MG', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'MECOBALAMIN 500 MCG', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'METOCLOPRAMIDE 10 MG', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'MICONAZOLE CREAM', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'NA DICLOFENAC 25 MG', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'NA DICLOFENAC 50 MG', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'NEUROBION FORTE', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'NEUROBION PUTIH', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'NIFEDIPINE 10 MG', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'NYSTATIN ORAL DROP', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'NYSTATIN VAGINAL TAB', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'ORALIT', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'PARACETAMOL SYRUP', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'PREDNISONE 5 MG', 'stok' => 40, 'lokasi' => '-'],
            ['nama_obat' => 'PROPRANOLOL 10 MG', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'PROPRANOLOL 40 MG', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'PYRANTEL PAMOAT 125 MG', 'stok' => 10, 'lokasi' => '-'],
            ['nama_obat' => 'RAMIPRIL 5 MG', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'SALBUTAMOL 2 MG', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'SALBUTAMOL 4 MG', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'SALICYL BEDAK', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'SPIRONOLACTONE 100 MG', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'THIAMINE (VIT B1) 50 MG', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'VITAMIN B12', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'VITAMIN C 50 MG', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'VITAMIN C 500 MG', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'ACARBOSE 50 MG', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'ACARBOSE 100 MG', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'AMLODIPINE 5 MG', 'stok' => 40, 'lokasi' => '-'],
            ['nama_obat' => 'AMLODIPINE 10 MG', 'stok' => 40, 'lokasi' => '-'],
            ['nama_obat' => 'ANTASIDA DOEN TAB', 'stok' => 30, 'lokasi' => '-'],
            ['nama_obat' => 'ANTASIDA DOEN SYRUP', 'stok' => 20, 'lokasi' => '-'],
            ['nama_obat' => 'ASAM TRANEXAMAT 500 MG', 'stok' => 20, 'lokasi' => '-'],

        ];

        foreach ($medicines as $medicine) {
            Medicine::create($medicine);
        }
    }
}
